[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Joe <burtonjae@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
